# Generated by Django 4.1.7 on 2023-03-02 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(default="", max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(default="", max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="middle_name",
            field=models.CharField(default="", max_length=15),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="StudentAdditionalInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reg_no", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
                ("school_email", models.EmailField(max_length=254)),
                ("faculty", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("programme", models.CharField(max_length=100)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("100 LEVEL", "L1"),
                            ("200 LEVEL", "L2"),
                            ("300 LEVEL", "L3"),
                            ("400 LEVEL", "L4"),
                            ("500 LEVEL", "L5"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "session",
                    models.CharField(
                        choices=[("2021/2022", "S2021"), ("2022/2023", "S2022")],
                        max_length=10,
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("FIRST SEMESTER", "First"),
                            ("SECOND SEMESTER", "Second"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "entry_mode",
                    models.CharField(
                        choices=[("UTME", "Utme"), ("DIRECT_ENTRY", "Direct Entry")],
                        max_length=20,
                    ),
                ),
                ("entry_year", models.CharField(max_length=4)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
