databases:
  - name: eksuict
    databaseName: eksuict
    user: admin

services:
  - type: web
    name: eksuict
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn edusploit.wsgi.application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: eksuict
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4