# Generated by Django 4.1.7 on 2023-03-02 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Billable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Billing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fees_name", models.CharField(max_length=200)),
                ("fees_description", models.TextField()),
                (
                    "session",
                    models.CharField(
                        choices=[("2021/2022", "S2021"), ("2022/2023", "S2022")],
                        max_length=10,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("100 LEVEL", "L1"),
                            ("200 LEVEL", "L2"),
                            ("300 LEVEL", "L3"),
                            ("400 LEVEL", "L4"),
                            ("500 LEVEL", "L5"),
                        ],
                        max_length=15,
                    ),
                ),
                ("due_date", models.DateTimeField()),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref_id", models.CharField(max_length=15)),
                (
                    "total_paid_fees",
                    models.DecimalField(decimal_places=2, max_digits=9),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("failed", "Failed"),
                            ("successful", "Successful"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "billable",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.billable",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="billable",
            name="billing",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.billing",
            ),
        ),
        migrations.AddField(
            model_name="billable",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="billables",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
